export type AppErrorCode =
  | 'UNKNOWN_ERROR'
  | 'NETWORK_ERROR'
  | 'FILE_SYSTEM_ERROR'
  | 'MODEL_CONFIGURATION_ERROR'
  | 'EMBEDDING_RUNTIME_ERROR'
  | 'MEMORY_INDEX_ERROR'
  | 'IPC_HANDLER_ERROR'
  | 'PROCESS_ERROR'
